#ifndef _NET_JAVA_SIP_COMMUNICATOR_WINDOWS_SETUP_H_
#define _NET_JAVA_SIP_COMMUNICATOR_WINDOWS_SETUP_H_

#include <windows.h>

#define IDS_ISWOW64ACCEPTABLE2 2
#define IDS_ISWOW64ACCEPTABLE3 3

#endif /* #ifndef _NET_JAVA_SIP_COMMUNICATOR_WINDOWS_SETUP_H_ */
