/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_plugin_msoutlook_MsOutlookAddressBookContactSourceService */

#ifndef _Included_net_java_sip_communicator_plugin_msoutlook_MsOutlookAddressBookContactSourceService
#define _Included_net_java_sip_communicator_plugin_msoutlook_MsOutlookAddressBookContactSourceService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_sip_communicator_plugin_msoutlook_MsOutlookAddressBookContactSourceService
 * Method:    MAPIInitialize
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_plugin_msoutlook_MsOutlookAddressBookContactSourceService_MAPIInitialize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_java_sip_communicator_plugin_msoutlook_MsOutlookAddressBookContactSourceService
 * Method:    MAPIUninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_plugin_msoutlook_MsOutlookAddressBookContactSourceService_MAPIUninitialize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
