/*
 * SIP Communicator, the OpenSource Java VoIP and Instant Messaging client.
 *
 * Distributable under LGPL license.
 * See terms of license at gnu.org.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_impl_neomedia_directshow_DSManager */

#ifndef _Included_net_java_sip_communicator_impl_neomedia_directshow_DSManager
#define _Included_net_java_sip_communicator_impl_neomedia_directshow_DSManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSManager
 * Method:    init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSManager_init
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSManager
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSManager_destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSManager
 * Method:    getCaptureDevices
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSManager_getCaptureDevices
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
