/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_impl_neomedia_directshow_DSFormat */

#ifndef _Included_net_java_sip_communicator_impl_neomedia_directshow_DSFormat
#define _Included_net_java_sip_communicator_impl_neomedia_directshow_DSFormat
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSFormat
 * Method:    getRGB24PixelFormat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSFormat_getRGB24PixelFormat
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSFormat
 * Method:    getRGB32PixelFormat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSFormat_getRGB32PixelFormat
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSFormat
 * Method:    getARGBPixelFormat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSFormat_getARGBPixelFormat
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSFormat
 * Method:    getAYUVPixelFormat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSFormat_getAYUVPixelFormat
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSFormat
 * Method:    getYUY2PixelFormat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSFormat_getYUY2PixelFormat
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSFormat
 * Method:    getUYVYPixelFormat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSFormat_getUYVYPixelFormat
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSFormat
 * Method:    getIMC1PixelFormat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSFormat_getIMC1PixelFormat
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSFormat
 * Method:    getIMC2PixelFormat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSFormat_getIMC2PixelFormat
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSFormat
 * Method:    getIMC3PixelFormat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSFormat_getIMC3PixelFormat
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSFormat
 * Method:    getIMC4PixelFormat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSFormat_getIMC4PixelFormat
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSFormat
 * Method:    getYV12PixelFormat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSFormat_getYV12PixelFormat
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSFormat
 * Method:    getNV12PixelFormat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSFormat_getNV12PixelFormat
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSFormat
 * Method:    getIF09PixelFormat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSFormat_getIF09PixelFormat
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSFormat
 * Method:    getIYUVPixelFormat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSFormat_getIYUVPixelFormat
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSFormat
 * Method:    getY211PixelFormat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSFormat_getY211PixelFormat
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSFormat
 * Method:    getY411PixelFormat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSFormat_getY411PixelFormat
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSFormat
 * Method:    getY41PPixelFormat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSFormat_getY41PPixelFormat
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSFormat
 * Method:    getYVU9PixelFormat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSFormat_getYVU9PixelFormat
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_directshow_DSFormat
 * Method:    getYVYUPixelFormat
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_directshow_DSFormat_getYVYUPixelFormat
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
