/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureSession */

#ifndef _Included_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureSession
#define _Included_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureSession
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureSession
 * Method:    addInput
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureSession_addInput
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureSession
 * Method:    addOutput
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureSession_addOutput
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureSession
 * Method:    allocAndInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureSession_allocAndInit
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureSession
 * Method:    startRunning
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureSession_startRunning
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureSession
 * Method:    stopRunning
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureSession_stopRunning
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
