/*
 * SIP Communicator, the OpenSource Java VoIP and Instant Messaging client.
 *
 * Distributable under LGPL license.
 * See terms of license at gnu.org.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDevice */

#ifndef _Included_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDevice
#define _Included_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDevice
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDevice_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDevice
 * Method:    formatDescriptions
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDevice_formatDescriptions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDevice
 * Method:    inputDevicesWithMediaType
 * Signature: (Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDevice_inputDevicesWithMediaType
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDevice
 * Method:    isConnected
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDevice_isConnected
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDevice
 * Method:    localizedDisplayName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDevice_localizedDisplayName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDevice
 * Method:    open
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDevice_open
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDevice
 * Method:    uniqueID
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDevice_uniqueID
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
