/*
 * SIP Communicator, the OpenSource Java VoIP and Instant Messaging client.
 *
 * Distributable under LGPL license.
 * See terms of license at gnu.org.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_impl_neomedia_quicktime_NSMutableDictionary */

#ifndef _Included_net_java_sip_communicator_impl_neomedia_quicktime_NSMutableDictionary
#define _Included_net_java_sip_communicator_impl_neomedia_quicktime_NSMutableDictionary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_NSMutableDictionary
 * Method:    allocAndInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_NSMutableDictionary_allocAndInit
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_NSMutableDictionary
 * Method:    setIntForKey
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_NSMutableDictionary_setIntForKey
  (JNIEnv *, jclass, jlong, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
