/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDecompressedVideoOutput */

#ifndef _Included_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDecompressedVideoOutput
#define _Included_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDecompressedVideoOutput
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDecompressedVideoOutput
 * Method:    allocAndInit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDecompressedVideoOutput_allocAndInit
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDecompressedVideoOutput
 * Method:    minimumVideoFrameInterval
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDecompressedVideoOutput_minimumVideoFrameInterval
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDecompressedVideoOutput
 * Method:    pixelBufferAttributes
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDecompressedVideoOutput_pixelBufferAttributes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDecompressedVideoOutput
 * Method:    setAutomaticallyDropsLateVideoFrames
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDecompressedVideoOutput_setAutomaticallyDropsLateVideoFrames
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDecompressedVideoOutput
 * Method:    setDelegate
 * Signature: (JLnet/java/sip/communicator/impl/neomedia/quicktime/QTCaptureDecompressedVideoOutput/Delegate;)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDecompressedVideoOutput_setDelegate
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDecompressedVideoOutput
 * Method:    setMinimumVideoFrameInterval
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDecompressedVideoOutput_setMinimumVideoFrameInterval
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDecompressedVideoOutput
 * Method:    setPixelBufferAttributes
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDecompressedVideoOutput_setPixelBufferAttributes
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
