/*
 * SIP Communicator, the OpenSource Java VoIP and Instant Messaging client.
 *
 * Distributable under LGPL license.
 * See terms of license at gnu.org.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDeviceInput */

#ifndef _Included_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDeviceInput
#define _Included_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDeviceInput
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDeviceInput
 * Method:    deviceInputWithDevice
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTCaptureDeviceInput_deviceInputWithDevice
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
