/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_impl_neomedia_quicktime_CVPixelBuffer */

#ifndef _Included_net_java_sip_communicator_impl_neomedia_quicktime_CVPixelBuffer
#define _Included_net_java_sip_communicator_impl_neomedia_quicktime_CVPixelBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_CVPixelBuffer
 * Method:    getBytes
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_CVPixelBuffer_getBytes
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
