/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_impl_neomedia_quicktime_QTFormatDescription */

#ifndef _Included_net_java_sip_communicator_impl_neomedia_quicktime_QTFormatDescription
#define _Included_net_java_sip_communicator_impl_neomedia_quicktime_QTFormatDescription
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTFormatDescription
 * Method:    sizeForKey
 * Signature: (JLjava/lang/String;)Ljava/awt/Dimension;
 */
JNIEXPORT jobject JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTFormatDescription_sizeForKey
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_QTFormatDescription
 * Method:    VideoEncodedPixelsSizeAttribute
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_QTFormatDescription_VideoEncodedPixelsSizeAttribute
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
