/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_impl_neomedia_quicktime_NSDictionary */

#ifndef _Included_net_java_sip_communicator_impl_neomedia_quicktime_NSDictionary
#define _Included_net_java_sip_communicator_impl_neomedia_quicktime_NSDictionary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_NSDictionary
 * Method:    intForKey
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_NSDictionary_intForKey
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
