/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_impl_neomedia_quicktime_CVPixelBufferAttributeKey */

#ifndef _Included_net_java_sip_communicator_impl_neomedia_quicktime_CVPixelBufferAttributeKey
#define _Included_net_java_sip_communicator_impl_neomedia_quicktime_CVPixelBufferAttributeKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_CVPixelBufferAttributeKey
 * Method:    kCVPixelBufferHeightKey
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_CVPixelBufferAttributeKey_kCVPixelBufferHeightKey
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_CVPixelBufferAttributeKey
 * Method:    kCVPixelBufferPixelFormatTypeKey
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_CVPixelBufferAttributeKey_kCVPixelBufferPixelFormatTypeKey
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_quicktime_CVPixelBufferAttributeKey
 * Method:    kCVPixelBufferWidthKey
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_quicktime_CVPixelBufferAttributeKey_kCVPixelBufferWidthKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
