/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_cef_CefBase */

#ifndef _Included_org_jitsi_cef_CefBase
#define _Included_org_jitsi_cef_CefBase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_cef_CefBase
 * Method:    _init_
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_cef_CefBase__1init_1
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jitsi_cef_CefBase
 * Method:    AddRef
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_cef_CefBase_AddRef
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jitsi_cef_CefBase
 * Method:    GetRefCt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_cef_CefBase_GetRefCt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_jitsi_cef_CefBase
 * Method:    Release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_cef_CefBase_Release
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
