/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_cef_CefSettings */

#ifndef _Included_org_jitsi_cef_CefSettings
#define _Included_org_jitsi_cef_CefSettings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_cef_CefSettings
 * Method:    _delete_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_cef_CefSettings__1delete_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_cef_CefSettings
 * Method:    _new_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_cef_CefSettings__1new_1
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_cef_CefSettings
 * Method:    isMultiThreadedMessageLoop
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_cef_CefSettings_isMultiThreadedMessageLoop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_cef_CefSettings
 * Method:    isSingleProcess
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_cef_CefSettings_isSingleProcess
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_cef_CefSettings
 * Method:    setMultiThreadedMessageLoop
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_cef_CefSettings_setMultiThreadedMessageLoop
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jitsi_cef_CefSettings
 * Method:    setSingleProcess
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_cef_CefSettings_setSingleProcess
  (JNIEnv *, jclass, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
