/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_cef_CefMainArgs */

#ifndef _Included_org_jitsi_cef_CefMainArgs
#define _Included_org_jitsi_cef_CefMainArgs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_cef_CefMainArgs
 * Method:    _delete_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_cef_CefMainArgs__1delete_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_cef_CefMainArgs
 * Method:    _new_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_cef_CefMainArgs__1new_1
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
