/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_cef_CefLifeSpanHandler */

#ifndef _Included_org_jitsi_cef_CefLifeSpanHandler
#define _Included_org_jitsi_cef_CefLifeSpanHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_cef_CefLifeSpanHandler
 * Method:    _alloc_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_cef_CefLifeSpanHandler__1alloc_1
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
