/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_cef_CefApp */

#ifndef _Included_org_jitsi_cef_CefApp
#define _Included_org_jitsi_cef_CefApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_cef_CefApp
 * Method:    CefInitialize
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jitsi_cef_CefApp_CefInitialize
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_jitsi_cef_CefApp
 * Method:    _alloc_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_cef_CefApp__1alloc_1
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
