/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_cef_CefWindowInfo */

#ifndef _Included_org_jitsi_cef_CefWindowInfo
#define _Included_org_jitsi_cef_CefWindowInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_cef_CefWindowInfo
 * Method:    _delete_
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_cef_CefWindowInfo__1delete_1
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_cef_CefWindowInfo
 * Method:    _new_
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_cef_CefWindowInfo__1new_1
  (JNIEnv *, jclass);

/*
 * Class:     org_jitsi_cef_CefWindowInfo
 * Method:    SetAsChild
 * Signature: (JJIIII)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_cef_CefWindowInfo_SetAsChild
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
