/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_plugin_addrbook_msoutlook_MsOutlookAddrBookContactSourceService */

#ifndef _Included_net_java_sip_communicator_plugin_addrbook_msoutlook_MsOutlookAddrBookContactSourceService
#define _Included_net_java_sip_communicator_plugin_addrbook_msoutlook_MsOutlookAddrBookContactSourceService
#ifdef __cplusplus
extern "C" {
#endif

#include <mapidefs.h>
#include <mapix.h>
#include <Unknwn.h>

/*
 * Class:     net_java_sip_communicator_plugin_addrbook_msoutlook_MsOutlookAddrBookContactSourceService
 * Method:    MAPIInitialize
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_plugin_addrbook_msoutlook_MsOutlookAddrBookContactSourceService_MAPIInitialize
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_java_sip_communicator_plugin_addrbook_msoutlook_MsOutlookAddrBookContactSourceService
 * Method:    MAPIUninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_plugin_addrbook_msoutlook_MsOutlookAddrBookContactSourceService_MAPIUninitialize
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL
Java_net_java_sip_communicator_plugin_addrbook_msoutlook_MsOutlookAddrBookContactSourceService_setDelegate
    (JNIEnv *jniEnv, jclass clazz, jobject callback);

void callInsertedCallbackMethod(
        LPUNKNOWN iUnknown);

void callUpdatedCallbackMethod(
        LPUNKNOWN iUnknown);

void callDeletedCallbackMethod(
        LPSTR iUnknown);

LPMAPISESSION MsOutlookAddrBookContactSourceService_getMapiSession();

#ifdef __cplusplus
}
#endif
#endif
