/*
 * Jitsi, the OpenSource Java VoIP and Instant Messaging client.
 *
 * Copyright @ 2015 Atlassian Pty Ltd
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_impl_galagonotification_GalagoNotification */

#ifndef _Included_net_java_sip_communicator_impl_galagonotification_GalagoNotification
#define _Included_net_java_sip_communicator_impl_galagonotification_GalagoNotification
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_sip_communicator_impl_galagonotification_GalagoNotification
 * Method:    dbus_bus_get_session
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_galagonotification_GalagoNotification_dbus_1bus_1get_1session
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_galagonotification_GalagoNotification
 * Method:    dbus_connection_unref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_impl_galagonotification_GalagoNotification_dbus_1connection_1unref
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_sip_communicator_impl_galagonotification_GalagoNotification
 * Method:    getCapabilities
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_net_java_sip_communicator_impl_galagonotification_GalagoNotification_getCapabilities
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_sip_communicator_impl_galagonotification_GalagoNotification
 * Method:    notify
 * Signature: (JLjava/lang/String;JLjava/awt/image/BufferedImage;Ljava/lang/String;Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_galagonotification_GalagoNotification_notify
  (JNIEnv *, jclass, jlong, jstring, jlong, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
