/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_plugin_msofficecomm_Messenger */

#ifndef _Included_net_java_sip_communicator_plugin_msofficecomm_Messenger
#define _Included_net_java_sip_communicator_plugin_msofficecomm_Messenger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_sip_communicator_plugin_msofficecomm_Messenger
 * Method:    onContactStatusChange
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_plugin_msofficecomm_Messenger_onContactStatusChange
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
