/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer */

#ifndef _Included_net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer
#define _Included_net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer
 * Method:    addNotifyLightweightComponent
 * Signature: (JLjava/awt/Component;J)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer_addNotifyLightweightComponent
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer
 * Method:    close
 * Signature: (JLjava/awt/Component;)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer_close
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer
 * Method:    open
 * Signature: (Ljava/awt/Component;)J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer_open
  (JNIEnv *, jclass, jobject);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer
 * Method:    paint
 * Signature: (JLjava/awt/Component;Ljava/awt/Graphics;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer_paint
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer
 * Method:    paintLightweightComponent
 * Signature: (JLjava/awt/Component;Ljava/awt/Graphics;)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer_paintLightweightComponent
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer
 * Method:    process
 * Signature: (JLjava/awt/Component;[IIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer_process
  (JNIEnv *, jclass, jlong, jobject, jintArray, jint, jint, jint, jint);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer
 * Method:    processLightweightComponentEvent
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer_processLightweightComponentEvent
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer
 * Method:    removeNotifyLightweightComponent
 * Signature: (JLjava/awt/Component;)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer_removeNotifyLightweightComponent
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer
 * Method:    sysctlbyname
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_java_sip_communicator_impl_neomedia_jmfext_media_renderer_video_JAWTRenderer_sysctlbyname
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
