/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_impl_neomedia_codec_audio_g722_JNIEncoder */

#ifndef _Included_net_java_sip_communicator_impl_neomedia_codec_audio_g722_JNIEncoder
#define _Included_net_java_sip_communicator_impl_neomedia_codec_audio_g722_JNIEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_java_sip_communicator_impl_neomedia_codec_audio_g722_JNIEncoder
 * Method:    g722_encoder_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_impl_neomedia_codec_audio_g722_JNIEncoder_g722_1encoder_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_codec_audio_g722_JNIEncoder
 * Method:    g722_encoder_open
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_java_sip_communicator_impl_neomedia_codec_audio_g722_JNIEncoder_g722_1encoder_1open
  (JNIEnv *, jclass);

/*
 * Class:     net_java_sip_communicator_impl_neomedia_codec_audio_g722_JNIEncoder
 * Method:    g722_encoder_process
 * Signature: (J[BI[BII)V
 */
JNIEXPORT void JNICALL Java_net_java_sip_communicator_impl_neomedia_codec_audio_g722_JNIEncoder_g722_1encoder_1process
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
