/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_java_sip_communicator_impl_dns_UnboundApi_UnboundCallback */

#ifndef _Included_net_java_sip_communicator_impl_dns_UnboundApi_UnboundCallback
#define _Included_net_java_sip_communicator_impl_dns_UnboundApi_UnboundCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
