##
# \file Makefile
# \brief Win32 (gcc) makefile.
# \author Sebastien Vincent

CC = gcc -m32
JNI_HEADERS = -I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/win32
CFLAGS = -shared $(JNI_HEADERS) -D_JNI_IMPLEMENTATION

LocalhostRetriever.dll: net_java_sip_communicator_impl_netaddr_Win32LocalhostRetriever.c
	$(CC) $(CFLAGS) net_java_sip_communicator_impl_netaddr_Win32LocalhostRetriever.c -liphlpapi -o $@

clean:
	del *.dll *.o

