CC = g++ -O2
TARGET_BASENAME = libjunbound.so

CPPFLAGS = \
	-Wall -Wreturn-type \
	-fpic \
	-DJNI_IMPLEMENTATION \
	-I/usr/lib/jvm/java-6-openjdk/include

LDFLAGS = -shared
LIBS = -lunbound
TARGET = $(TARGET_BASENAME)

$(TARGET): src/*.cpp
	$(CC) $(CPPFLAGS) $^ $(LDFLAGS) -o $@ $(LIBS)
	-strip $(TARGET)
